site_name: Jeremy.Richards.Dev

docs_dir: content/
theme:
    name: null
    custom_dir: layout/

nav:
    - Resume: 'cv.md'
    - Contact: 'contact.md'
    - Knowledge Base: 'kb'
    - Links: 'links'
