site_name: Jeremy.Richards.Dev
site_url: https://test.richards.dev
repo_url: https://github.com/jeremysprofile/jeremysprofile.github.io

docs_dir: content/
theme:
  name: null
  custom_dir: layout/
  static_templates:
    - '404.html'
    - 'search.html'
    - 'sitemap.xml'

nav:
  - Resume: 'cv.md'
  - Contact: 'contact.md'
  - Knowledge Base: 'kb'
  - Links: 'links'
