name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: gh-deploy
        run: |
          pip3 install "mkdocs==1.2.1" "jinja2==3.0.1"
          python3 --version
          mkdocs --version
          python -c 'import jinja2; print(jinja2.__version__)'
          echo "wtf"
          mkdocs gh-deploy
